### ISSUE TITLE
Regular task using extools is broken

### ISSUE THREAD

**Issue by NewProggie** [ocroquette/gradle-extools#3]
When executing an extool task using the regular task (such as task doStuff {...} the following error occurs

    * What went wrong:
    Execution failed for task ':doStuff'.
    > Cannot get property 'variablesToPrependInEnv' on null object

Using the same extools package from within an extools task (type:ExtoolExec) however, executes nicely.

**Comment by oliver124810** [comment]
Your task probably miss the dependency on extoolsLoad. I want to improve the error message at some point.

**Comment by oliver124810** [comment]
v1.13 provides a useful error message in this case
