### ISSUE TITLE
[RFE] Crossplatform support?

### ISSUE THREAD

**Issue by cqjjjzr** [ocroquette/gradle-extools#4]
Hi.
As we know the external tools are often platform-specfied, on different OSs/archs they have different versions. I wonder if there is any support for that by this plugin.
Thanks.

**Comment by oliver124810** [comment]
Hi Charlie, I typically use different extools for the different platforms I need to support, and use a naming convention to differentiate the ("doxygen-x.y-win", "doxygen-x.y-mac"). Another option is to put them in a single package and set different variables to the different subdirectories.
