### ISSUE TITLE
[RFE] Better plugin fetch method?

### ISSUE THREAD

**Issue by cqjjjzr** [ocroquette/gradle-extools#5]
Hi.
This plugin is really GREAT. But I think it may be a little confusing if we use a custom repo format for ext tools. Most times we need to use plugins not written by ourselves, so it's hard for us to maintain a repo for this. This may be a main limitation of this plugin.
In my opinion, it will be great if the plugin can automaticlly recognize some different formats, the most important, Jenkins, Travis CI, AppVeyor and GitHub releases. Custom repo resolver is also needed. It should allow us to provide a custom Groovy(or Java?) script to grab the version and download info from the correct place, so we can resolve custom repos like https://thrift.apache.org/download .
Thanks.

**Comment by oliver124810** [comment]
Hi Charlie, thanks for the feedback, I am glad you like the plugin. Check out some of the sample recipes to create extools here: https://github.com/ocroquette/gradle-extools-recipes
I have currently no plans to support other repositories, sorry.

**Comment by cqjjjzr** [comment]
Am I permitted to write code to support other repo and send a PR here?

**Comment by oliver124810** [comment]
If you need it, you should do it :) But I cannot promise I will merge it, it depends on the impact on the source code and the how useful it is for other users, including me.
